export * from './BasePage';
export * from './BasicAuthPage';
export * from './CartPage';
export * from './CheckBoxPage';
export * from './FramesetPage';
export * from './HomePage';
export * from './HTMLElementsPage';
export * from './InventoryPage';
export * from './LoginPage';
